# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thru < Formula
  desc "Pure throughput. Zero friction."
  homepage "https://github.com/samsungplay/thruflux"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.1.1/thru_v0.1.1_darwin_amd64.tar.gz"
      sha256 "fcb598d581b2828d17cd498e2c75b4d499d41d57c38b1688a11788fa68016b1b"

      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.1.1/thru_v0.1.1_darwin_arm64.tar.gz"
      sha256 "c8fd1748f1ff0a217131a4f942a89c1ef5c2bfd54b6203cd1c37c41b733f37b1"

      def install
        bin.install "thru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.1.1/thru_v0.1.1_linux_amd64.tar.gz"
      sha256 "c29d0b6637369bf03eaf3b7eb998608c9375d26126485da67cfb0b9fee07f8c5"
      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.1.1/thru_v0.1.1_linux_arm64.tar.gz"
      sha256 "b1681dda54d4c332b871a1c52f83f958d14eca6e6c8e164489bf211f1615f595"
      def install
        bin.install "thru"
      end
    end
  end

  test do
    system "#{bin}/thru", "--version"
  end
end
