# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thru < Formula
  desc "Pure throughput. Zero friction."
  homepage "https://github.com/samsungplay/thruflux"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.2.0/thru_v0.2.0_darwin_amd64.tar.gz"
      sha256 "54b4e941f20f12a73fce1dec6e2d3f526f6feb76c4cb882cf218961b85e80dce"

      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.2.0/thru_v0.2.0_darwin_arm64.tar.gz"
      sha256 "b7437689137d79f39e2ec147a1c7e3b4952ad8ed8f07d81bd074512bf4f87878"

      def install
        bin.install "thru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.2.0/thru_v0.2.0_linux_amd64.tar.gz"
      sha256 "76827bef27993c96fec5ed733560684ee1703ea19c46f0b1eb41c2d9870a7cc9"
      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsungplay/Thruflux/releases/download/v0.2.0/thru_v0.2.0_linux_arm64.tar.gz"
      sha256 "d2f163b99e88937bd172fc539dcd1536b8df58be6c55174bcef4da4a37295d95"
      def install
        bin.install "thru"
      end
    end
  end

  test do
    system "#{bin}/thru", "--version"
  end
end
